print("----------")
print("cadastro")
print("----------")
nome = input("digita seu nome")
email = input("digita seu email")
escola = input("digite o nome da sua escola")
print("----------")
print("cadrastro concluido")
print("----------")
print(f"usuario: {nome}")
print(f"email: {email}")
print(f"escola:{escola}")
